### ISSUE TITLE
如何部署到服务器？

### ISSUE THREAD

**Issue by sunscheung** [huangwei9527/quark-h5#24]
前后端分别部署：
前端：
1. npm run build-client 并将dist目录放到服务器指定目录下，如：**/quark-h5/client
2.配置ningx

后端：
1. 将server目录代码复制到服务器指定目录下,如：**/quark-h5/server
2. 切换到**/quark-h5/server目录下，执行 npm install pm2 -g & npm run start

数据库：
安装MongoDB，创建quark数据库

@huangwei9527 目前部署线上是这个样子吗

**Comment by littlelioncjt** [comment]
请问您这样部署成功了吗？
