### ISSUE TITLE
本地项目发送请求报错

### ISSUE THREAD

**Issue by xuxihua** [huangwei9527/quark-h5#9]
clone下来后在本地运行，在login/register界面发送请求均显示 连接到服务器失败

**Comment by xuxihua** [comment]
已经解决了，是数据库权限问题

**Comment by 1146612734** [comment]
> 已经解决了，是数据库权限问题

怎么解决的？也遇到了这个问题

**Comment by huangwei9527** [comment]
数据库如果链接需要账号密码改下config配置
`module.exports = {
	port: 4000,
	mongodb: {
		url: 'mongodb://localhost:27017/quark',
		options: {
			auth: { authSource: "admin" },
			user: 'admin',
			pass: 'admin'
		}
	},
	middleware:['handlerError'],
	jwt: {secret: 'huangwei9527'},
	crypto: {secret: '#*#*huangwei9527*#*#'},
	baseUrl: ''
}
`
